package com.tiktokviewer.domain.model

enum class SearchSource {
    LIGHT_ENGINE_MOBILE_API,
    LIGHT_ENGINE_WEB_API,
    LIGHT_ENGINE_HTML_SCRAPE,
    HEAVY_ENGINE_WEBVIEW,
    HEAVY_ENGINE_INTERCEPTED_API,
    PEER_NETWORK,
    SERVER_PROXY_TIER_1,
    SERVER_PROXY_TIER_2,
    SERVER_PROXY_TIER_3,
    LOCAL_CACHE
}
