package com.tiktokviewer.domain.model

enum class SignalType {
    SEARCH_QUERY,
    SEARCH_CLICK,
    VIDEO_START,
    VIDEO_WATCH_25,
    VIDEO_WATCH_50,
    VIDEO_WATCH_75,
    VIDEO_WATCH_100,
    VIDEO_SKIP,
    VIDEO_REWATCH,
    VIDEO_REPLAY_BUTTON,
    VIDEO_PAUSE,
    VIDEO_SHARE,
    VIDEO_EXTERNAL_LINK,
    SCROLL_PATTERN,
    SESSION_DURATION,
    TIME_OF_DAY,
    WATCHED_FULL_SEQUENCE,
    NOT_INTERESTED
}
